/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_rental_system;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author harsha pariyani
 */
public class EmployeeDetails extends javax.swing.JFrame {

    //private Object ps;
    ResultSet rs=null;
    PreparedStatement ps=null;
    Connection conn= null;
    Statement smt;

    /**
     * Creates new form EmployeeDeatils
     */
    public EmployeeDetails() {
       initComponents();
   }
    static final String DB_URL = "jdbc:mysql://localhost:3306/car_rental";
    static final String DB_DRV = "com.mysql.cj.jdbc.Driver";
    static final String DB_USER = "root";
    static final String DB_PASSWD = "Harsha123";
    Connection con=null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Eid = new javax.swing.JTextField();
        Ename = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Eaddress = new javax.swing.JTextArea();
        EDOB = new javax.swing.JTextField();
        Eemailid = new javax.swing.JTextField();
        Elicenseno = new javax.swing.JTextField();
        Eavailable = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        Ephoneno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 0, 470, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 80, 147, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 130, 73, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DOB :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 180, 66, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 270, 97, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email-ID :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 340, 109, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("License No :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 400, 127, 28);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Availability :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 470, 134, 28);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone No :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 530, 160, 40);

        Add.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(770, 160, 240, 37);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Delete");
        jPanel1.add(jButton3);
        jButton3.setBounds(770, 370, 250, 37);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("Update");
        jPanel1.add(jButton4);
        jButton4.setBounds(770, 260, 240, 37);
        jPanel1.add(Eid);
        Eid.setBounds(300, 80, 180, 30);
        jPanel1.add(Ename);
        Ename.setBounds(300, 130, 180, 30);

        Eaddress.setColumns(20);
        Eaddress.setRows(5);
        jScrollPane1.setViewportView(Eaddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 240, 180, 90);
        jPanel1.add(EDOB);
        EDOB.setBounds(300, 180, 180, 30);
        jPanel1.add(Eemailid);
        Eemailid.setBounds(300, 340, 170, 30);

        Elicenseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElicensenoActionPerformed(evt);
            }
        });
        jPanel1.add(Elicenseno);
        Elicenseno.setBounds(300, 400, 170, 30);
        jPanel1.add(Eavailable);
        Eavailable.setBounds(300, 470, 170, 30);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("Retrive");
        jPanel1.add(jButton5);
        jButton5.setBounds(770, 470, 250, 37);
        jPanel1.add(Ephoneno);
        Ephoneno.setBounds(300, 540, 170, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 640, 170, 37);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental_system/mypicture.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 4, 1500, 900);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElicensenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElicensenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElicensenoActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        //CustomerConnection obj;
        //obj = new CustomerConnection();
        //obj.setVisible(true);
        //this.setVisible(false);
      
        String Eidtext=Eid.getText();
        String Enametext=Ename.getText();
        String EDOBtext=EDOB.getText();
        String Eaddresstext=Eaddress.getText();
        String Eemailidtext=Eemailid.getText();
        String Elicensenotext=Elicenseno.getText();
        String Eavailabletext=Eavailable.getText();
        String Ephonenotext=Ephoneno.getText();
        
        
      
         try{
        
            con=DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWD);
            
        ps = con.prepareStatement("insert into employee values(?,?,?,?,?,?,?,?)");
       
         ps.setString(1,Eidtext);
                ps.setString(2,Enametext);
                ps.setString(3,EDOBtext);
                ps.setString(4,Eaddresstext);
                ps.setString(5,Eemailidtext);
                ps.setString(6,Elicensenotext);
                ps.setString(7,Eavailabletext);
               ps.setString(8,Ephonenotext);
        ps.executeUpdate();
   
        }catch(SQLException e){
            System.out.println(e);
        }
        //DriverManager con; /*try {
              
                
        
    }//GEN-LAST:event_AddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ChooseYourOption obj;
        obj = new ChooseYourOption();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EmployeeDetails().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField EDOB;
    private javax.swing.JTextArea Eaddress;
    private javax.swing.JTextField Eavailable;
    private javax.swing.JTextField Eemailid;
    private javax.swing.JTextField Eid;
    private javax.swing.JTextField Elicenseno;
    private javax.swing.JTextField Ename;
    private javax.swing.JTextField Ephoneno;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
