/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_rental_system;
import static car_rental_system.EmployeeDetails.DB_URL;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author harsha pariyani
 */
public class FourSeaterBooking extends javax.swing.JFrame {
 ResultSet rs=null;
    PreparedStatement ps=null;
    Connection conn= null;
    Statement smt;
    /**
     * Creates new form FourSeaterBooking
     */
    public FourSeaterBooking() {
        initComponents();
    }
    static final String DB_URL = "jdbc:mysql://localhost:3306/car_rental";
    static final String DB_DRV = "com.mysql.cj.jdbc.Driver";
    static final String DB_USER = "root";
    static final String DB_PASSWD = "Harsha123";
    Connection con=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Book = new javax.swing.JButton();
        Cchooseyourcar = new javax.swing.JComboBox<>();
        Cid = new javax.swing.JTextField();
        Cname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Caddress = new javax.swing.JTextArea();
        Cemailid = new javax.swing.JTextField();
        Cphoneno = new javax.swing.JTextField();
        Clicenseno = new javax.swing.JTextField();
        Fstartdate = new javax.swing.JTextField();
        Fenddate = new javax.swing.JTextField();
        Fstarttime = new javax.swing.JTextField();
        Fendtime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Ftotalfare = new javax.swing.JTextField();
        Cvehicleid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Fpickuppoint = new javax.swing.JComboBox<>();
        Fdestination = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        CDOB = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Four Seater Booking");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 0, 500, 56);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 110, 160, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 160, 110, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 220, 130, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email ID :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 320, 140, 28);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone NO :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 380, 140, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("License No :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 440, 160, 28);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pick-up Point :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(620, 100, 155, 28);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Destination :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(620, 160, 131, 28);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Start Date :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(620, 240, 120, 28);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("End Date :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(620, 310, 110, 28);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Start Time :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(620, 380, 124, 28);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("End Time :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(620, 440, 130, 28);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Choose Your Car :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(230, 590, 240, 28);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 650, 120, 37);

        Book.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Book.setText("Book");
        Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookActionPerformed(evt);
            }
        });
        jPanel1.add(Book);
        Book.setBounds(1040, 650, 120, 37);

        Cchooseyourcar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Cchooseyourcar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maruti Ciaz Rs100/hr", "Maruti Swift Rs100/hr", "Hyundai Elite Rs120/hr", "Tata Tiago Rs160/hr", "Honda Brio Rs150/hr" }));
        jPanel1.add(Cchooseyourcar);
        Cchooseyourcar.setBounds(460, 590, 300, 28);

        Cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidActionPerformed(evt);
            }
        });
        jPanel1.add(Cid);
        Cid.setBounds(260, 110, 180, 30);

        Cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnameActionPerformed(evt);
            }
        });
        jPanel1.add(Cname);
        Cname.setBounds(260, 160, 180, 30);

        Caddress.setColumns(20);
        Caddress.setRows(5);
        jScrollPane1.setViewportView(Caddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(260, 210, 180, 90);
        jPanel1.add(Cemailid);
        Cemailid.setBounds(260, 320, 180, 30);
        jPanel1.add(Cphoneno);
        Cphoneno.setBounds(260, 380, 180, 30);
        jPanel1.add(Clicenseno);
        Clicenseno.setBounds(260, 440, 180, 30);
        jPanel1.add(Fstartdate);
        Fstartdate.setBounds(860, 240, 180, 30);
        jPanel1.add(Fenddate);
        Fenddate.setBounds(860, 310, 180, 30);

        Fstarttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FstarttimeActionPerformed(evt);
            }
        });
        jPanel1.add(Fstarttime);
        Fstarttime.setBounds(860, 380, 180, 30);
        jPanel1.add(Fendtime);
        Fendtime.setBounds(860, 440, 180, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Fare :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(620, 510, 170, 28);

        Ftotalfare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FtotalfareActionPerformed(evt);
            }
        });
        jPanel1.add(Ftotalfare);
        Ftotalfare.setBounds(860, 510, 180, 30);

        Cvehicleid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CvehicleidActionPerformed(evt);
            }
        });
        jPanel1.add(Cvehicleid);
        Cvehicleid.setBounds(460, 630, 300, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Vehicle ID :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(230, 630, 160, 28);

        Fpickuppoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pune", "Mumbai", "Mahabaleshwar", "Lonavala" }));
        jPanel1.add(Fpickuppoint);
        Fpickuppoint.setBounds(860, 100, 180, 30);

        Fdestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pune", "Mumbai", "Mahabaleshwar", "Lonavala" }));
        jPanel1.add(Fdestination);
        Fdestination.setBounds(860, 160, 180, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DOB");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(60, 510, 100, 28);

        CDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDOBActionPerformed(evt);
            }
        });
        jPanel1.add(CDOB);
        CDOB.setBounds(260, 510, 180, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_rental_system/mypicture.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(0, 0, 1410, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookActionPerformed
        // TODO add your handling code here:
        fourCongrates obj;
        obj = new fourCongrates();
        obj.setVisible(true);
        this.setVisible(false);
        
        String Cidtext=Cid.getText();
        String Cnametext=Cname.getText();
        String Caddresstext=Caddress.getText();
        String Cemailidtext=Cemailid.getText();
        String Cphonenotext=Cphoneno.getText();
        String  Clicensenotext=Clicenseno.getText();
        String  CDOBtext=CDOB.getText();
       
        
        String Fpickuppointtext=Cid.getText();
        String Fdestinationtext=Cname.getText();
        String Fstartdatetext=Caddress.getText();
        String Fenddatetext=Cemailid.getText();
        String Fstarttimetext=Cphoneno.getText();
        String Fendtimetext=Clicenseno.getText();
        String Ftotalfaretext=CDOB.getText();
        
       
        
      
         try{
        
            con=DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWD);
            
        ps = con.prepareStatement("insert into customer values(?,?,?,?,?,?,?,)");
       
         ps.setString(1,Fpickuppointtext);
         ps.setString(2,Fdestinationtext);
         ps.setString(3,Fstartdatetext);
         ps.setString(4,Fenddatetext);
         ps.setString(5,Fstarttimetext);
         ps.setString(6,Fendtimetext);
         ps.setString(7,Ftotalfaretext);
        
         ps.executeUpdate();
         
         ps = con.prepareStatement("insert into four_seater_Booking values(?,?,?,?,?,?,?,)");
         
         ps.setString(1,Cidtext);
         ps.setString(2,Cnametext);
         ps.setString(3,Caddresstext);
         ps.setString(4,Cemailidtext);
         ps.setString(5,Cphonenotext);
         ps.setString(6,Clicensenotext);
         ps.setString(7,CDOBtext);
   
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_BookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnameActionPerformed

    private void CidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidActionPerformed

    private void FtotalfareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FtotalfareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FtotalfareActionPerformed

    private void CvehicleidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CvehicleidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CvehicleidActionPerformed

    private void FstarttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FstarttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FstarttimeActionPerformed

    private void CDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDOBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FourSeaterBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FourSeaterBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FourSeaterBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FourSeaterBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FourSeaterBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Book;
    private javax.swing.JTextField CDOB;
    private javax.swing.JTextArea Caddress;
    private javax.swing.JComboBox<String> Cchooseyourcar;
    private javax.swing.JTextField Cemailid;
    private javax.swing.JTextField Cid;
    private javax.swing.JTextField Clicenseno;
    private javax.swing.JTextField Cname;
    private javax.swing.JTextField Cphoneno;
    private javax.swing.JTextField Cvehicleid;
    private javax.swing.JComboBox<String> Fdestination;
    private javax.swing.JTextField Fenddate;
    private javax.swing.JTextField Fendtime;
    private javax.swing.JComboBox<String> Fpickuppoint;
    private javax.swing.JTextField Fstartdate;
    private javax.swing.JTextField Fstarttime;
    private javax.swing.JTextField Ftotalfare;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
